//! Generate a starter behavior config from an OpenAPI spec: one endpoint rule
//! per spec operation, pre-filled with inert example behavior so the output is
//! self-documenting yet safe to run unedited. Powers `--scaffold-config`.

use crate::config::model::{
    Behavior, EndpointRule, LatencySpec, MethodMatch, MockConfig, RateLimitSpec,
};
use crate::openapi::model::OpenApiDoc;

/// `#`-comment banner prepended to the serialized YAML. serde can't emit
/// comments, so knobs we deliberately don't pre-fill are documented here.
pub const SCAFFOLD_BANNER: &str = "\
# Generated by `mock-mesh --scaffold-config`. Edit freely.
# The latency/rate_limit values below are inert examples — trim what you
# don't need. Other per-endpoint knobs (not pre-filled):
#   error_mode: { kind: status, code: 500, probability: 0.1 }
#   error_mode: { kind: hang, max_secs: 30 }
#   error_mode: { kind: abort }
#   response:   { status: 200, body: { ok: true } }   # replaces the spec body
";

/// Build a scaffold `MockConfig` covering every operation in `spec`.
///
/// Deterministic: `paths` is a `BTreeMap` (sorted) and `operations()` yields a
/// fixed method order. The example values pass the loader's own validation
/// (`rps > 0`, `burst >= 1`), so the result round-trips straight back in.
pub fn scaffold(spec: &OpenApiDoc) -> MockConfig {
    let mut endpoints = Vec::new();
    for (raw_path, item) in &spec.paths {
        for (method, _op) in item.operations() {
            endpoints.push(EndpointRule {
                path: raw_path.clone(),
                method: MethodMatch::One(method),
                behavior: Behavior {
                    latency: Some(LatencySpec {
                        fixed_ms: 0,
                        jitter_ms: 0,
                    }),
                    rate_limit: Some(RateLimitSpec {
                        rps: 100.0,
                        burst: 10,
                        reject_probability: 0.0,
                        response_status: 429,
                    }),
                    error_mode: None,
                },
                response: None,
            });
        }
    }
    MockConfig {
        defaults: Behavior::default(),
        endpoints,
    }
}

#[cfg(test)]
mod tests {
    #![allow(clippy::unwrap_used)]

    use super::*;
    use crate::config::model::MockConfig;
    use http::Method;

    fn spec_from(yaml: &str) -> OpenApiDoc {
        serde_yaml_ng::from_str(yaml).unwrap()
    }

    #[test]
    fn one_entry_per_operation_sorted_and_typed() {
        let spec = spec_from(
            r#"
openapi: "3.0.0"
paths:
  /pets:
    get: { responses: {} }
    post: { responses: {} }
  /pets/{petId}:
    get: { responses: {} }
"#,
        );
        let cfg = scaffold(&spec);
        assert_eq!(cfg.endpoints.len(), 3);
        // BTreeMap sorts paths; operations() puts GET before POST.
        assert_eq!(cfg.endpoints[0].path, "/pets");
        assert_eq!(cfg.endpoints[0].method, MethodMatch::One(Method::GET));
        assert_eq!(cfg.endpoints[1].path, "/pets");
        assert_eq!(cfg.endpoints[1].method, MethodMatch::One(Method::POST));
        assert_eq!(cfg.endpoints[2].path, "/pets/{petId}");
    }

    #[test]
    fn output_round_trips_through_the_loader() {
        let spec = spec_from(
            r#"
openapi: "3.1.0"
paths:
  /a: { get: { responses: {} } }
  /b: { delete: { responses: {} } }
"#,
        );
        let cfg = scaffold(&spec);
        let yaml = serde_yaml_ng::to_string(&cfg).unwrap();
        let reparsed: MockConfig = serde_yaml_ng::from_str(&yaml).unwrap();
        assert_eq!(reparsed.endpoints.len(), 2);
        // Example behavior must satisfy the loader's validation.
        for ep in &reparsed.endpoints {
            ep.behavior.validate(&ep.path).unwrap();
        }
    }
}
